version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: spring_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourPassword
    ports:
      - "8080:8080"

volumes:
  pgdata:
